#!/usr/bin/env python3
"""Build src/font437.h: 8x16 and 8x8 CP437 fonts from Linux console PSF fonts
(kbd / console-setup-linux, /usr/share/consolefonts). Only needed to regenerate
the checked-in header.  Usage: tools/mkfont.py > src/font437.h"""
import gzip, sys

DIR = "/usr/share/consolefonts/"
# CP437 code points 0..255 as Unicode (0 and 32 are blanks)
CP437 = ([0x0000, 0x263A, 0x263B, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022,
          0x25D8, 0x25CB, 0x25D9, 0x2642, 0x2640, 0x266A, 0x266B, 0x263C,
          0x25BA, 0x25C4, 0x2195, 0x203C, 0x00B6, 0x00A7, 0x25AC, 0x21A8,
          0x2191, 0x2193, 0x2192, 0x2190, 0x221F, 0x2194, 0x25B2, 0x25BC]
         + list(range(0x20, 0x7F)) + [0x2302] +
         [ord(c) for c in bytes(range(0x80, 0x100)).decode("cp437")])


def load_psf(name):
    d = gzip.open(DIR + name).read()
    if d[:2] == b"\x36\x04":                       # PSF1
        mode, h = d[2], d[3]
        n = 512 if mode & 1 else 256
        glyphs = [d[4 + i * h:4 + (i + 1) * h] for i in range(n)]
        p, umap, g = 4 + n * h, {}, 0
        while g < n and p + 1 < len(d):
            u = d[p] | d[p + 1] << 8
            p += 2
            if u == 0xFFFF:
                g += 1
            elif u != 0xFFFE:
                umap.setdefault(u, g)
        return h, glyphs, umap
    raise SystemExit(name + ": not PSF1")


# stand-ins for glyphs no console font has (code point, mirror horizontally)
ALT = {0x25BA: [(0x25B6, 0), (0x25B8, 0)], 0x25C4: [(0x25C0, 0), (0x25C2, 0)],
       0x2310: [(0x00AC, 1)], 0x221E: [(0x38, 0)], 0x2229: [(0x6E, 0)],
       0x2261: [(0x2263, 0), (0x3D, 0)], 0x20A7: [(0x50, 0)]}


def mirror(g):
    return bytes(int("{:08b}".format(b)[::-1], 2) for b in g)


def table(h, files):
    fonts = [load_psf(f) for f in files]
    out = []
    for i, u in enumerate(CP437):
        for c, flip in [(u, 0)] + ALT.get(u, []):
            g = next((gl[um[c]] for fh, gl, um in fonts if c in um), None)
            if g is not None:
                out.append(mirror(g) if flip else g)
                break
        else:
            if u not in (0,):
                sys.stderr.write("missing U+%04X (cp437 %d)\n" % (u, i))
            out.append(bytes(h))
    return out


def emit(name, h, rows):
    print("static const unsigned char %s[256 * %d] = {" % (name, h))
    for i, g in enumerate(rows):
        print("  " + ",".join("0x%02x" % b for b in g) + ",  /* %d */" % i)
    print("};")


print("/* CP437 fonts generated by tools/mkfont.py from the Linux console fonts")
print("   (kbd / console-setup), which are in the public domain / GPL. */")
emit("font8x16", 16, table(16, ["FullGreek-VGA16.psf.gz", "Uni2-VGA16.psf.gz", "Lat15-VGA16.psf.gz", "Vietnamese-Terminus16.psf.gz"]))
emit("font8x8", 8, table(8, ["Uni2-VGA8.psf.gz", "FullGreek-VGA8.psf.gz", "Lat15-VGA8.psf.gz"]))
